In [1]:
# In the rare disease example, what is the probability of having the disease given that, 
# 1. you have tested positive at first test 
# 2. you have tested positive at first and second test 
# 3. you have tested positive at first test and negative at second test.
# x is the average probability of having the disease; y is the reliability of the test.
# n is the no. of positive test; m is the no. of negative test

# 1, 2, 3
def probability_of_disease(x, y, n, m):
    return 1/(1+(((1-y)**n)*(y**m))*(1-x)/(x*(y**n)*(1-y)**m))
  
probability_of_disease(0.001, 0.99,2,1)


0.09016393442622943

In [3]:
# check no. of cores
import multiprocessing as mp
print(mp.cpu_count())

16


In [2]:
import numpy as np
import matplotlib.pyplot as plt
from ler.utils import get_param_from_json
from scipy.stats import gaussian_kde

from ler.rates import LeR

In [3]:
# initialize LeR
ler = LeR(
    # SNR related
    sampling_frequency =  2048,
    waveform_approximant =  'IMRPhenomD',
    minimum_frequency =  20.0,
    snr_type =  'interpolation',
    ifos =  ['L1','H1','V1'],
    # GW related
    source_priors= {
        'merger_rate_density': 'merger_rate_density_bbh_popI_II_oguri2018', 
        'source_frame_masses': 'binary_masses_BBH_popI_II_powerlaw_gaussian', 
        'zs': 'sample_source_redshift', 
        'geocent_time': 'sampler_uniform', 
        'ra': 'sampler_uniform', 
        'dec': 'sampler_cosine', 
        'phase': 'sampler_uniform', 
        'psi': 'sampler_uniform', 
        'theta_jn': 'sampler_sine'
        },      
    source_priors_params= {
        'merger_rate_density': {'R0': 2.39e-08, 'b2': 1.6, 'b3': 2.1, 'b4': 30.}, 
        'source_frame_masses': {'mminbh': 4.59, 'mmaxbh': 86.22, 'alpha': 2.63, 'mu_g': 33.07, 'sigma_g': 5.69, 'lambda_peak': 0.10, 'delta_m': 4.82, 'beta': 1.26}, 
        'zs': None, 
        'geocent_time': {'min_': 1238166018, 'max_': 1269702018}, 
        'ra': {'min_': 0.0, 'max_': 6.283185307179586}, 
        'dec': None, 
        'phase': {'min_': 0.0, 'max_': 6.283185307179586}, 
        'psi': {'min_': 0.0, 'max_': 3.141592653589793}, 
        'theta_jn': None
        },
    spin_zero= True,
    spin_precession= False,
    # lens related
    lens_type =  'epl_galaxy',
    lens_functions =  {
        'strong_lensing_condition': 'rjs_with_cross_section_SIS', 
        'optical_depth': 'optical_depth_SIS_haris', 
        'param_sampler_type': 'sample_all_routine',
        },
    lens_priors =  {
        'source_redshift_sl': 'strongly_lensed_source_redshifts', 
        'lens_redshift': 'lens_redshift_SDSS_catalogue', 
        'velocity_dispersion': 'velocity_dispersion_gengamma', 
        'axis_ratio': 'axis_ratio_rayleigh', 
        'axis_rotation_angle': 'axis_rotation_angle_uniform', 
        'shear': 'shear_norm', 
        'mass_density_spectral_index': 'mass_density_spectral_index_normal', 
        'source_parameters': 'sample_gw_parameters',
        },
    lens_priors_params =  {
        'source_redshift_sl': None, 
        'lens_redshift': None, 
        'velocity_dispersion': {'a':2.32 / 2.67, 'c':2.67}, 
        'axis_ratio': {'q_min': 0.2, 'q_max': 1.0}, 
        'axis_rotation_angle': {'phi_min': 0.0, 'phi_max': 2*np.pi}, 
        'shear': {'scale': 0.05}, 
        'mass_density_spectral_index': {'mean': 2.0, 'std': 0.2}, 'source_parameters': None
    },
    # image related
    n_min_images = 2,
    n_max_images = 4,
    lens_model_list =  ['EPL_NUMBA', 'SHEAR'],
)


z_to_luminosity_distance interpolator will be loaded from ./interpolator_pickle/z_to_luminosity_distance/z_to_luminosity_distance_0.pickle
differential_comoving_volume interpolator will be loaded from ./interpolator_pickle/differential_comoving_volume/differential_comoving_volume_0.pickle
merger_rate_density_bbh_popI_II_oguri2018 interpolator will be loaded from ./interpolator_pickle/merger_rate_density_bbh_popI_II_oguri2018/merger_rate_density_bbh_popI_II_oguri2018_1.pickle
z_to_Dc interpolator will be loaded from ./interpolator_pickle/z_to_Dc/z_to_Dc_0.pickle
Dc_to_z interpolator will be loaded from ./interpolator_pickle/Dc_to_z/Dc_to_z_0.pickle
angular_diameter_distance interpolator will be loaded from ./interpolator_pickle/angular_diameter_distance/angular_diameter_distance_0.pickle
differential_comoving_volume interpolator will be loaded from ./interpolator_pickle/differential_comoving_volume/differential_comoving_volume_1.pickle
velocity_dispersion_gengamma interpolator will be l

2024-06-29 13:12:15.335551: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-29 13:12:15.425962: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-29 13:12:16.031336: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-29 13:12:16.035821: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-29 13:12:17.300902: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

npool:  4
snr type:  interpolation
waveform approximant:  IMRPhenomD
sampling frequency:  2048
minimum frequency (fmin):  20.0
mtot=mass1+mass2
min(mtot):  2.0
max(mtot) (with the given fmin=20.0): 184.98599853446768
detectors:  None
min(ratio):  0.1
max(ratio):  1.0
mtot resolution:  500
ratio resolution:  50
interpolator directory:  ./interpolator_pickle
Interpolator will be loaded for L1 detector from ./interpolator_pickle/L1/partialSNR_dict_0.pickle
Interpolator will be loaded for H1 detector from ./interpolator_pickle/H1/partialSNR_dict_0.pickle
Interpolator will be loaded for V1 detector from ./interpolator_pickle/V1/partialSNR_dict_1.pickle

 LeR set up params:
npool =  4
z_min =  0.0
z_max =  10.0
event_type =  BBH
size =  100000
batch_size =  50000
cosmology =  LambdaCDM(H0=70.0 km / (Mpc s), Om0=0.3, Ode0=0.7, Tcmb0=0.0 K, Neff=3.04, m_nu=None, Ob0=None)
snr_finder =  <bound method GWSNR.snr of <gwsnr.gwsnr.GWSNR object at 0x7f2c109d4e50>>
json_file_names =  {'ler_params': 'l

In [4]:
# ler.batch_size = 100000 # for faster computation
unlensed_param = ler.unlensed_cbc_statistics(size=100000, resume=False, save_batch=False,output_jsonfile='unlensed_cbc_bbh.json')

_, unlensed_param_detectable = ler.unlensed_rate();

# ler.batch_size = 50000
lensed_param = ler.lensed_cbc_statistics(size=100000, resume=False, save_batch=False, output_jsonfile='lensed_cbc_bbh.json')

_, lensed_param_detectable = ler.lensed_rate();

ler.rate_ratio();
# rate_ratio, unlensed_param_detectable, lensed_param_detectable = ler.rate_comparision_with_rate_calculation()


unlensed params will be store in ./ler_data/unlensed_cbc_bbh.json
chosen batch size = 50000 with total size = 100000
There will be 2 batche(s)
Batch no. 1
sampling gw source params...
calculating snrs...
Batch no. 2
sampling gw source params...
calculating snrs...
saving all unlensed_params in ./ler_data/unlensed_cbc_bbh.json...
getting unlensed_params from json file ./ler_data/unlensed_cbc_bbh.json...
given detectability_condition == 'step_function'
total unlensed rate (yr^-1) (with step function): 1018.665302268693
number of simulated unlensed detectable events: 984
number of all simulated unlensed events: 100000
storing detectable unlensed params in ./ler_data/unlensed_param_detectable.json
lensed params will be store in ./ler_data/lensed_cbc_bbh.json
chosen batch size = 50000 with total size = 100000
There will be 2 batche(s)
Batch no. 1
sampling lensed params...
solving lens equations...


100%|████████████████████████████████████████████████████████| 50000/50000 [00:51<00:00, 971.18it/s]


calculating snrs...
Batch no. 2
sampling lensed params...
solving lens equations...


100%|████████████████████████████████████████████████████████| 50000/50000 [01:01<00:00, 815.90it/s]


Invalid sample found. Resampling 2 lensed events...
solving lens equations...


100%|█████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.68s/it]


calculating snrs...
saving all lensed_params in ./ler_data/lensed_cbc_bbh.json...
getting lensed_params from json file ./ler_data/lensed_cbc_bbh.json...
given detectability_condition == 'step_function'
total lensed rate (yr^-1) (with step function): 0.7429248944361975
number of simulated lensed detectable events: 735
number of simulated all lensed events: 100000
storing detectable lensed params in ./ler_data/lensed_param_detectable.json
unlensed_rate: 1018.665302268693
lensed_rate: 0.7429248944361975
ratio: 1371.1551596904742


In [5]:
lensed_param_detectable = get_param_from_json('./ler_data/lensed_param_detectable.json')
snr = lensed_param_detectable['optimal_snr_net']
print(snr)

[[ 5.8348104  10.11220265 11.1424184   5.87834215]
 [12.7996451  10.42896172  7.9862931   0.        ]
 [ 2.38098694 10.87793207 10.21947747  5.59940677]
 ...
 [13.18900042  7.43813576 13.18544792  0.        ]
 [ 3.77616436 11.94355908 10.76819151  2.65123419]
 [ 8.00616781  9.95963045  0.          0.        ]]


In [7]:
# ratio of double, triple and quadruple images
idx1 = abs(lensed_param_detectable['optimal_snr_net'])>8
idx2 = np.sum(idx1, axis=1)
ratio_double = np.sum(idx2==2)/len(idx2)
ratio_triple = np.sum(idx2==3)/len(idx2)
ratio_quadruple = np.sum(idx2==4)/len(idx2)
print(ratio_double)
print(ratio_triple)
print(ratio_quadruple)

0.7034013605442176
0.2054421768707483
0.09115646258503401


In [92]:
# time delay

time_delay = lensed_param_detectable['time_delays']
snr = lensed_param_detectable['optimal_snr_net']

idx1 = abs(snr)>8
idx2 = np.sum(idx1, axis=1)

combined = np.column_stack([idx2, time_delay])
print(combined)

[[2.00000000e+00 0.00000000e+00 6.19877031e+05 6.64157561e+05
  1.14358832e+06]
 [2.00000000e+00 0.00000000e+00 1.10552260e+06 4.64156569e+06
  0.00000000e+00]
 [2.00000000e+00 0.00000000e+00 1.91519990e+06 1.91543876e+06
  1.95871118e+06]
 ...
 [2.00000000e+00 0.00000000e+00 4.04851605e+04 6.85904215e+05
  0.00000000e+00]
 [2.00000000e+00 0.00000000e+00 3.13105319e+06 3.13743154e+06
  7.17285327e+06]
 [2.00000000e+00 0.00000000e+00 3.96879148e+07 0.00000000e+00
  0.00000000e+00]]


In [55]:
combined = ()

# Reshape the 1D array to have the same number of dimensions as the 4D array
reshaped_array_1d = idx2[:, np.newaxis, np.newaxis, np.newaxis]

# Concatenate the arrays along a new axis
combined = np.concatenate((reshaped_array_1d[..., np.newaxis]), time_delay, axis=1)

t_double_img = [[row[1:5] for row in sublist if sublist[0] == 2] for sublist in combined]

TypeError: concatenate() got multiple values for argument 'axis'

In [ ]:
time_double_img = [row["time"] for row in zip(data["time"], data["image"]) if idx2 == 2]
time_triple_img = np.array(row["time"] for row in data if row["image"] == 3)
time_quadruple_img = np.array(row["time"] for row in data if row["image"] == 4)
'''
this is for 1-d time_delay array:
data = {"time": time_delay, "image": idx2} 
time_double_image = [t for t, time_delay in zip(data["time"], data["image"]) if idx2 == 2]
'''
'''
my previous failed version:
time_delay_double = [];
time_delay_triple = [];
time_delay_quadruple = [];
for i in idx2:
    if i == 2:
        time_delay_double.append(time_delay[i]) 
    elif i == 3:
        time_delay_triple.append(time_delay[i])
    else:
        time_delay_quadruple.append(time_delay[i])
'''

In [25]:
dt_eff = lensed_param_detectable['time_delays']
print(dt_eff)

[[       0.           619877.03062256   664157.56077742  1143588.32010244]
 [       0.          1105522.59720378  4641565.68998829        0.        ]
 [       0.          1915199.89696738  1915438.75657793  1958711.18462601]
 ...
 [       0.            40485.16051307   685904.21529793        0.        ]
 [       0.          3131053.1898965   3137431.54424434  7172853.26780279]
 [       0.         39687914.75653023        0.                0.        ]]


In [ ]:


# double-image
dt_eff = lensed_params_detectable['time_delays']
time_double_img = np.array(row["time"] for row in data if row["image"] == 2)

dt12 = abs(dt_eff[:,1]-dt_eff[:,0])/ (24*3600)
dt13 = abs(dt_eff[:,2]-dt_eff[:,0])/ (24*3600)
dt14 = abs(dt_eff[:,3]-dt_eff[:,0])/ (24*3600)

# select only detectable
snr_l = lensed_params_detectable['optimal_snr_net']
dt12 = dt12[snr_l[:,1]>8]
dt13 = dt13[snr_l[:,2]>8]
dt14 = dt14[snr_l[:,3]>8]

# select only non-nan values
dt12 = dt12[~np.isnan(dt12)]
dt12 = dt12[~np.isnan(dt12)]
dt12 = dt12[~np.isnan(dt12)]

log_t12 = np.log10(dt12)
log_t13 = np.log10(dt13)
log_t14 = np.log10(dt14)
# plot time delays
plt.figure(figsize=(6, 4))
plt.hist(log_t12, bins=30, alpha=0.8, label='dt12', density=True, histtype='step')
plt.hist(log_t13, bins=30, alpha=0.8, label='dt13', density=True, histtype='step')
plt.hist(log_t14, bins=30, alpha=0.8, label='dt14', density=True, histtype='step')
plt.legend()
plt.grid(alpha=0.4)
plt.xlabel(r'dt [log10(days)]')
plt.ylabel(r'$P(dt)$')
plt.title('Time delays wrt to first image')
plt.show()

In [66]:
from pylab import *
log(e) # NOT RECOMMENDED 

1.0

In [69]:
a = np.array([1,2,3,4,5])
print(a)
print(a[0],a[4]) # beware, very different in other languages !
print(len(a))   # how long is an array ? 

b = np.append(a,6) # append element to an array, leaves original array intact
print(b)
a = np.append(a,[6,7,8,9,10]) # if you want to change the original array
print (a)

[1 2 3 4 5]
1 5
5
[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10]


In [74]:
mylist = [1,2,3,4]
mylist.append(5) # actually changes the list ! Compare to Numpy arrays. Disgusting, huh ? 
print(mylist)

[1, 2, 3, 4, 5]


In [78]:
l = [1,2,3]
l.append([6,7]) # should append individual elements 6 and 7, right ?
print (l)           # woah, what happened ?

l.extend([8,9,10,11])    # this is what we really meant
print (l)
l.extend(['12', int(13)]) # mixing types is allowed for list
print(l)

[1, 2, 3, [6, 7]]
[1, 2, 3, [6, 7], 8, 9, 10, 11]
[1, 2, 3, [6, 7], 8, 9, 10, 11, '12', 13]


In [84]:
print(mylist * 5)
print(np.array(mylist)*5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [85]:
# Some basics 
a = np.array([-1, 7, 8, 100, -20.2])
b = np.array(range(20))
print(a)
print(b)
print (a[0])      # indexing
print (a[-1])
print (a[:3])     # slicing
print (b[5:10])
print (b[::2])   # striding
print (b[4:15:3]) # [start:stop:skip]

[ -1.    7.    8.  100.  -20.2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
-1.0
-20.2
[-1.  7.  8.]
[5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 4  7 10 13]


In [87]:
# These will always be full of zeros
print (np.zeros(5))
print (np.zeros([3,4,5]))

[0. 0. 0. 0. 0.]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [88]:
print (np.zeros([2,2], dtype='bool'))
print (np.ones([2,2], dtype='bool'))

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


In [90]:
m = np.zeros([3,3], dtype = float)
m[0,:]=[1,2,3]
m[1,:]=[4,5,6]
m[2,:]=[7,8,9]
print (m)
print (m[0,1])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2.0


In [91]:
u = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])
v = np.array([1,2,3])
print (u*v,"\n")            
print (np.matmul(u,v),"\n") # this is how numpy does linear algebra !
print (u*5)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[6 6 6] 

[[5 5 5]
 [5 5 5]
 [5 5 5]]
